FROM php:7.2-apache
LABEL maintainer="Ghostry <ghostry.green@gmail.com>"

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-install iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd mbstring mysqli pdo pdo_mysql shmop \
    && /usr/sbin/a2enmod rewrite
