FROM php:5.6-fpm

LABEL maintainer="Ghostry <ghostry.green@gmail.com>"

RUN apt-get update \
    && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev \
    && apt-get clean \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

RUN pecl install redis-4.0.1 && docker-php-ext-enable redis

RUN apt-get update \
    && apt-get install -y libmemcached-dev zlib1g-dev \
    && apt-get clean \
    && pecl install memcached-2.2.0 \
    && docker-php-ext-enable memcached

RUN docker-php-ext-install -j$(nproc) pdo_mysql bcmath calendar ctype exif gettext mysql mysqli opcache pcntl shmop zip

RUN curl -o ioncube.tar.gz https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz \
    && tar -xvvzf ioncube.tar.gz \
    && mv ioncube/ioncube_loader_lin_5.6.so `php-config --extension-dir` \
    && rm -Rf ioncube.tar.gz ioncube \
    && docker-php-ext-enable ioncube_loader_lin_5.6
