name: Publish 8.1.nginx

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile.8.1.nginx'
      - '8.1.nginx/start.sh'
      - '8.1.nginx/nginx.conf'
  workflow_dispatch:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: get_image_name
        run: |
          repository=${{ github.repository }}
          IMAGE_NAME=${{ github.actor }}/${repository##*/}

          echo IMAGE_NAME=$IMAGE_NAME

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        run: |
          docker build -f Dockerfile.8.1.nginx -t ${{ env.IMAGE_NAME }}:8.1-nginx .
          docker push ${{ env.IMAGE_NAME }}:8.1-nginx
